#!/usr/bin/env python
"""Bake the demo's sample customers into the frontend bundle.

    python scripts/build_samples.py

The frontend used to fetch these from `GET /api/examples`, which cost ~9s on a
cold start: `load_examples()` reads a 1ms file and then spends nearly all of
that time opening a connection to the remote database just to classify the
profiles. The buckets are computed once here, at build time, so the page can
render them immediately with no request at all.

Classification still comes from the engine's own ground truth — this script
calls the same `load_examples` the endpoint does, it just runs offline. Rerun it
after `make data` so the buckets match the catalogue.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "backend"))

from app.survey import load_examples  # noqa: E402

TARGET = REPO_ROOT / "frontend" / "src" / "lib" / "samples.ts"

HEADER = """// GENERATED by `python scripts/build_samples.py` — do not edit by hand.
//
// The bucket a profile sits in (clear fit / close call / not eligible) is
// computed by the rules engine, not chosen by hand, so this file is regenerated
// whenever the catalogue or the thresholds in policy.yaml change.

import type {{ ExampleBucket }} from "./types";

export const SAMPLES: ExampleBucket = {buckets};

export const SAMPLES_NOTE = {note};
"""


def main() -> None:
    data = load_examples()
    buckets = data["buckets"]
    body = HEADER.format(
        buckets=json.dumps(buckets, indent=2, ensure_ascii=False),
        note=json.dumps(data["note"], ensure_ascii=False),
    )
    TARGET.write_text(body, encoding="utf-8")
    counts = {k: len(v) for k, v in buckets.items()}
    print(f"samples      : {counts} -> {TARGET.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
