// GENERATED by `python scripts/build_samples.py` — do not edit by hand.
//
// The bucket a profile sits in (clear fit / close call / not eligible) is
// computed by the rules engine, not chosen by hand, so this file is regenerated
// whenever the catalogue or the thresholds in policy.yaml change.

import type { ExampleBucket } from "./types";

export const SAMPLES: ExampleBucket = {
  "recommended": [
    {
      "profile_id": "USER_0038",
      "profile": {
        "profile_id": "USER_0038",
        "age": 37,
        "monthly_income": 150000,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 738,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 23.9,
        "monthly_spend": {
          "fuel": 10600,
          "dining": 12800,
          "groceries": 14200,
          "online_shopping": 17000,
          "travel": 11600,
          "utilities": 10400,
          "other": 74400
        },
        "preferences": [
          "travel",
          "lifetime_free"
        ]
      }
    },
    {
      "profile_id": "USER_0052",
      "profile": {
        "profile_id": "USER_0052",
        "age": 43,
        "monthly_income": 150500,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 750,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 1,
        "utilization_pct": 33.8,
        "monthly_spend": {
          "fuel": 9900,
          "dining": 11500,
          "groceries": 15900,
          "online_shopping": 19400,
          "travel": 19000,
          "utilities": 10700,
          "other": 76200
        },
        "preferences": []
      }
    },
    {
      "profile_id": "USER_0053",
      "profile": {
        "profile_id": "USER_0053",
        "age": 49,
        "monthly_income": 155500,
        "employment": "salaried",
        "city_tier": 2,
        "cibil_score": 781,
        "existing_cards": 4,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 29.5,
        "monthly_spend": {
          "fuel": 6500,
          "dining": 11300,
          "groceries": 22500,
          "online_shopping": 10600,
          "travel": 10400,
          "utilities": 13100,
          "other": 63900
        },
        "preferences": [
          "fuel"
        ]
      }
    },
    {
      "profile_id": "USER_0056",
      "profile": {
        "profile_id": "USER_0056",
        "age": 30,
        "monthly_income": 449000,
        "employment": "self_employed",
        "city_tier": 1,
        "cibil_score": 552,
        "existing_cards": 3,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 3,
        "utilization_pct": 79.1,
        "monthly_spend": {
          "fuel": 43500,
          "dining": 39600,
          "groceries": 57700,
          "online_shopping": 35000,
          "travel": 17300,
          "utilities": 45400,
          "other": 140800
        },
        "preferences": [
          "cashback",
          "lifetime_free"
        ]
      }
    },
    {
      "profile_id": "USER_0067",
      "profile": {
        "profile_id": "USER_0067",
        "age": 54,
        "monthly_income": 165000,
        "employment": "salaried",
        "city_tier": 3,
        "cibil_score": 747,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 1,
        "utilization_pct": 19.7,
        "monthly_spend": {
          "fuel": 7300,
          "dining": 14100,
          "groceries": 19800,
          "online_shopping": 12100,
          "travel": 13700,
          "utilities": 16000,
          "other": 62100
        },
        "preferences": [
          "cashback",
          "lifetime_free"
        ]
      }
    },
    {
      "profile_id": "USER_0103",
      "profile": {
        "profile_id": "USER_0103",
        "age": 33,
        "monthly_income": 155000,
        "employment": "self_employed",
        "city_tier": 2,
        "cibil_score": 652,
        "existing_cards": 4,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 37.6,
        "monthly_spend": {
          "fuel": 9700,
          "dining": 16300,
          "groceries": 15500,
          "online_shopping": 13400,
          "travel": 11800,
          "utilities": 18700,
          "other": 80500
        },
        "preferences": [
          "cashback"
        ]
      }
    }
  ],
  "borderline": [
    {
      "profile_id": "USER_0001",
      "profile": {
        "profile_id": "USER_0001",
        "age": 23,
        "monthly_income": 17000,
        "employment": "student",
        "city_tier": 1,
        "cibil_score": 679,
        "existing_cards": 0,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 3,
        "utilization_pct": 11.0,
        "monthly_spend": {
          "fuel": 400,
          "dining": 1800,
          "groceries": 4600,
          "online_shopping": 2100,
          "travel": 1100,
          "utilities": 1100,
          "other": 5400
        },
        "preferences": [
          "travel",
          "lifetime_free"
        ]
      }
    },
    {
      "profile_id": "USER_0002",
      "profile": {
        "profile_id": "USER_0002",
        "age": 28,
        "monthly_income": 89000,
        "employment": "salaried",
        "city_tier": 3,
        "cibil_score": 696,
        "existing_cards": 1,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 3,
        "utilization_pct": 29.6,
        "monthly_spend": {
          "fuel": 5700,
          "dining": 6600,
          "groceries": 13200,
          "online_shopping": 17700,
          "travel": 6800,
          "utilities": 7800,
          "other": 34400
        },
        "preferences": [
          "travel"
        ]
      }
    },
    {
      "profile_id": "USER_0003",
      "profile": {
        "profile_id": "USER_0003",
        "age": 34,
        "monthly_income": 56500,
        "employment": "salaried",
        "city_tier": 2,
        "cibil_score": 746,
        "existing_cards": 3,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 28.7,
        "monthly_spend": {
          "fuel": 3300,
          "dining": 5100,
          "groceries": 5500,
          "online_shopping": 6100,
          "travel": 4600,
          "utilities": 6300,
          "other": 27000
        },
        "preferences": [
          "fuel"
        ]
      }
    },
    {
      "profile_id": "USER_0004",
      "profile": {
        "profile_id": "USER_0004",
        "age": 61,
        "monthly_income": 285000,
        "employment": "salaried",
        "city_tier": 3,
        "cibil_score": 758,
        "existing_cards": 5,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 1,
        "utilization_pct": 54.8,
        "monthly_spend": {
          "fuel": 17200,
          "dining": 19600,
          "groceries": 41600,
          "online_shopping": 14300,
          "travel": 29100,
          "utilities": 28900,
          "other": 131800
        },
        "preferences": [
          "travel"
        ]
      }
    },
    {
      "profile_id": "USER_0005",
      "profile": {
        "profile_id": "USER_0005",
        "age": 48,
        "monthly_income": 46500,
        "employment": "self_employed",
        "city_tier": 3,
        "cibil_score": 667,
        "existing_cards": 4,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 5.6,
        "monthly_spend": {
          "fuel": 3200,
          "dining": 3600,
          "groceries": 6300,
          "online_shopping": 3700,
          "travel": 2600,
          "utilities": 4800,
          "other": 18400
        },
        "preferences": []
      }
    },
    {
      "profile_id": "USER_0006",
      "profile": {
        "profile_id": "USER_0006",
        "age": 33,
        "monthly_income": 20000,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 680,
        "existing_cards": 0,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 3,
        "utilization_pct": 13.2,
        "monthly_spend": {
          "fuel": 800,
          "dining": 1300,
          "groceries": 3600,
          "online_shopping": 2100,
          "travel": 600,
          "utilities": 2500,
          "other": 7900
        },
        "preferences": [
          "travel"
        ]
      }
    }
  ],
  "rejected": [
    {
      "profile_id": "USER_0007",
      "profile": {
        "profile_id": "USER_0007",
        "age": 30,
        "monthly_income": 64500,
        "employment": "self_employed",
        "city_tier": 1,
        "cibil_score": 545,
        "existing_cards": 5,
        "missed_payments_12m": 1,
        "recent_inquiries_6m": 2,
        "utilization_pct": 74.4,
        "monthly_spend": {
          "fuel": 6400,
          "dining": 3800,
          "groceries": 7400,
          "online_shopping": 5200,
          "travel": 2700,
          "utilities": 6500,
          "other": 21600
        },
        "preferences": []
      }
    },
    {
      "profile_id": "USER_0014",
      "profile": {
        "profile_id": "USER_0014",
        "age": 27,
        "monthly_income": 40000,
        "employment": "self_employed",
        "city_tier": 1,
        "cibil_score": 441,
        "existing_cards": 5,
        "missed_payments_12m": 2,
        "recent_inquiries_6m": 1,
        "utilization_pct": 56.7,
        "monthly_spend": {
          "fuel": 2700,
          "dining": 2900,
          "groceries": 6400,
          "online_shopping": 5100,
          "travel": 1900,
          "utilities": 4700,
          "other": 14200
        },
        "preferences": [
          "cashback",
          "lifetime_free"
        ]
      }
    },
    {
      "profile_id": "USER_0021",
      "profile": {
        "profile_id": "USER_0021",
        "age": 44,
        "monthly_income": 83000,
        "employment": "self_employed",
        "city_tier": 2,
        "cibil_score": 398,
        "existing_cards": 5,
        "missed_payments_12m": 2,
        "recent_inquiries_6m": 2,
        "utilization_pct": 82.4,
        "monthly_spend": {
          "fuel": 6400,
          "dining": 5000,
          "groceries": 10700,
          "online_shopping": 8800,
          "travel": 3400,
          "utilities": 9900,
          "other": 35600
        },
        "preferences": [
          "travel"
        ]
      }
    },
    {
      "profile_id": "USER_0042",
      "profile": {
        "profile_id": "USER_0042",
        "age": 33,
        "monthly_income": 232000,
        "employment": "self_employed",
        "city_tier": 3,
        "cibil_score": 429,
        "existing_cards": 2,
        "missed_payments_12m": 2,
        "recent_inquiries_6m": 3,
        "utilization_pct": 44.4,
        "monthly_spend": {
          "fuel": 20300,
          "dining": 14400,
          "groceries": 28900,
          "online_shopping": 17400,
          "travel": 14400,
          "utilities": 18000,
          "other": 96200
        },
        "preferences": [
          "fuel"
        ]
      }
    },
    {
      "profile_id": "USER_0049",
      "profile": {
        "profile_id": "USER_0049",
        "age": 29,
        "monthly_income": 56500,
        "employment": "self_employed",
        "city_tier": 1,
        "cibil_score": 501,
        "existing_cards": 4,
        "missed_payments_12m": 1,
        "recent_inquiries_6m": 2,
        "utilization_pct": 69.6,
        "monthly_spend": {
          "fuel": 5000,
          "dining": 4000,
          "groceries": 9600,
          "online_shopping": 6100,
          "travel": 2900,
          "utilities": 5800,
          "other": 18500
        },
        "preferences": [
          "lounge"
        ]
      }
    },
    {
      "profile_id": "USER_0063",
      "profile": {
        "profile_id": "USER_0063",
        "age": 41,
        "monthly_income": 71500,
        "employment": "self_employed",
        "city_tier": 1,
        "cibil_score": 390,
        "existing_cards": 1,
        "missed_payments_12m": 2,
        "recent_inquiries_6m": 2,
        "utilization_pct": 87.0,
        "monthly_spend": {
          "fuel": 6800,
          "dining": 4500,
          "groceries": 13300,
          "online_shopping": 5400,
          "travel": 3200,
          "utilities": 7700,
          "other": 38300
        },
        "preferences": []
      }
    }
  ],
  "edge_case": [
    {
      "profile_id": "EDGE_INCOME_EXACT",
      "profile": {
        "profile_id": "EDGE_INCOME_EXACT",
        "age": 30,
        "monthly_income": 117000,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 740,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 20.0,
        "monthly_spend": {
          "fuel": 0,
          "dining": 0,
          "groceries": 0,
          "online_shopping": 10000,
          "travel": 0,
          "utilities": 0,
          "other": 5000
        },
        "preferences": [
          "cashback"
        ]
      }
    },
    {
      "profile_id": "EDGE_INCOME_MINUS1",
      "profile": {
        "profile_id": "EDGE_INCOME_MINUS1",
        "age": 30,
        "monthly_income": 116999,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 740,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 20.0,
        "monthly_spend": {
          "fuel": 0,
          "dining": 0,
          "groceries": 0,
          "online_shopping": 10000,
          "travel": 0,
          "utilities": 0,
          "other": 5000
        },
        "preferences": [
          "cashback"
        ]
      }
    },
    {
      "profile_id": "EDGE_INCOME_PLUS1",
      "profile": {
        "profile_id": "EDGE_INCOME_PLUS1",
        "age": 30,
        "monthly_income": 117001,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 740,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 20.0,
        "monthly_spend": {
          "fuel": 0,
          "dining": 0,
          "groceries": 0,
          "online_shopping": 10000,
          "travel": 0,
          "utilities": 0,
          "other": 5000
        },
        "preferences": [
          "cashback"
        ]
      }
    },
    {
      "profile_id": "EDGE_CIBIL_EXACT",
      "profile": {
        "profile_id": "EDGE_CIBIL_EXACT",
        "age": 30,
        "monthly_income": 580000,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 780,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 20.0,
        "monthly_spend": {
          "fuel": 0,
          "dining": 0,
          "groceries": 0,
          "online_shopping": 10000,
          "travel": 0,
          "utilities": 0,
          "other": 5000
        },
        "preferences": [
          "cashback"
        ]
      }
    },
    {
      "profile_id": "EDGE_CIBIL_MINUS1",
      "profile": {
        "profile_id": "EDGE_CIBIL_MINUS1",
        "age": 30,
        "monthly_income": 580000,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 779,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 20.0,
        "monthly_spend": {
          "fuel": 0,
          "dining": 0,
          "groceries": 0,
          "online_shopping": 10000,
          "travel": 0,
          "utilities": 0,
          "other": 5000
        },
        "preferences": [
          "cashback"
        ]
      }
    },
    {
      "profile_id": "EDGE_AGE_AT_MIN",
      "profile": {
        "profile_id": "EDGE_AGE_AT_MIN",
        "age": 23,
        "monthly_income": 95000,
        "employment": "salaried",
        "city_tier": 1,
        "cibil_score": 740,
        "existing_cards": 2,
        "missed_payments_12m": 0,
        "recent_inquiries_6m": 0,
        "utilization_pct": 20.0,
        "monthly_spend": {
          "fuel": 0,
          "dining": 0,
          "groceries": 0,
          "online_shopping": 10000,
          "travel": 0,
          "utilities": 0,
          "other": 5000
        },
        "preferences": [
          "cashback"
        ]
      }
    }
  ]
};

export const SAMPLES_NOTE = "Synthetic profiles generated from a fixed seed. No real people.";
